cc_library(
    name = "test_helpers",
    hdrs = [
        "test_helpers.hpp",
    ],
    srcs = [
        "test_helpers.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/logging",
        "@com_google_googletest//:gtest_main",
    ],
)

