cc_library(
    name = "opencv_utils",
    hdrs = [
        "opencv_utils.hpp",
    ],
    srcs = [
        "opencv_utils.cpp",
    ],
    visibility = ["//visibility:public"],
    includes = ["."],
    deps = [
        "//datatypes:MRA_cc_proto",
        "@opencv",
    ],
)

