// CODEGEN_NOTE
// it should NOT be modified by user

#ifndef _MRA_COMPONENT_CPP_NAME_UNDERSCORE_DATATYPES_HPP
#define _MRA_COMPONENT_CPP_NAME_UNDERSCORE_DATATYPES_HPP

PROTOBUF_HPP_TYPE_INCLUDES

#endif

