= GetBallIntercept Robotsports Variant

== Summary

GetBallIntercept is an action that to intercept the ball (catchting in the beak of the robot).

== Scope and context

This action implements the sub-action getball-intercept (get a rolling ball) of the getball action.
This variant is RobotSport variant of getball-intercept.

== Interface details

* **purpose**: get the ball
* **inputs**: See link:./interface/Input.proto[Input.proto] for the exact definition.
	** WorldState  

* **outputs**:  See link:./interface/Output.proto[Output.proto] for the exact definition.  
	** robot target set-point (type posvel in FCS) [to PathPlanning]
	** actionResult [to Reasoning]
	** estimated time to get the ball (s), for query/decisioning purpose [to Reasoning]

* *parameters*:  
The action has some configuration parameters. These parameters are specific for this variant of get ball intercept, 
see link:./interface/Params.proto[Params.proto] and 
link:./interface/DefaultParams.json[DefaultParams.json].

== Design

Calculate interception point for the robot. Interception point is the perpendicular towards the path of the ball. +
Only if the interception point is within parameter "actionradius" from the position of the robot it will return the interception point as target point. +
If the interception point is too far, the result will be set to FAILED and the target position to the current position of the robot.

== History

Created by Robotsports. 
 