cc_library(
    name = "reflexxes",
    hdrs = glob(["RMLTypeII/include/*.h"]),
    srcs = glob(["RMLTypeII/src/TypeIIRML/*.cpp"]),
    includes = ["RMLTypeII/include"],
    copts = ["-Wno-address"],
    visibility = ["//visibility:public"],
)

