
cc_binary(
    name = "tune",
    srcs = [
        "tune.cpp",
        "tuningtool.hpp",
        "tuningtool.cpp",
    ],
    deps = [
        "@opencv",
        "//components/falcons/localization-vision:implementation",
    ],
)

