cc_test(
    name = "test_mra_logger",
    srcs = [
        "test_mra_logger.cpp",
    ],
    deps = [
        "//components/robotsports/proof_is_alive:implementation",
        "@com_google_googletest//:gtest_main",
    ],
)

