cc_library(
    name = "testing_base",
    includes = ["."],
    hdrs = [
        "test_factory.hpp",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "abstract_interface",
    includes = ["."],
    hdrs = [
        "abstract_interface.hpp",
    ],
    visibility = ["//visibility:public"],
)
